---
abstract: 'Simple interaction with OpenERP XML RPC interface.'
author:
  - 'Benjamin Martin <ben@madeofpaper.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OpenERP-XMLRPC-Simple
requires:
  File::ShareDir: 1.02
  File::Slurp: 9999.13
  Moose: 1.15
  MooseX::Role::XMLRPC::Client: 0.04
  Net::HTTPServer: 1.1.1
  XML::Simple: 2.18
version: 0.001
